version: '3.8'

services:
  execution_engine:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 manage:app
#    volumes:
#      - ./flask-nginx-gunicorn-docker/:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env.prod

  nginx:
    build: ./nginx/
    ports:
      - 1337:80
    depends_on:
      - execution_engine